name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          server-id: github
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build with Maven
        run: mvn clean install

#      - name: Print DOCKER_USERNAME secret
#        run: echo "DOCKER_USERNAME:" ${{ secrets.DOCKER_USERNAME }}
#        env:
#          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#
#      - name: Print DOCKER_PASSWORD secret
#        run: echo "DOCKER_PASSWORD:" ${{ secrets.DOCKER_PASSWORD }}
#        env:
#          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to DockerHub
        run: |
          docker login -u dockermars123 -p docker.P@$$w0rd
          docker build -t iss_places_of_interest .
          docker tag iss_places_of_interest dockermars123/iss_places_of_interest:latest
          docker push dockermars123/iss_places_of_interest:latest
        

